version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ticketgateway-frontend
    overwrite: true
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/ticketgateway-frontend
    owner: ubuntu
    group: ubuntu
    mode: 777
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100
