version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ocureel-code  #my-cicd is the name of repository
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
