import React from 'react'
import './style.css'

const Index = () => {
  return (
    <div className='community__guidline'>
      <h1>Community Guidelines</h1>
      <h5>Last updated:</h5>
      <p> September 25th 2022 Ocureel's mission is to inspire authenticity and genuine connection. We are committed to maintaining a supportive environment for our growing community. Our Community Guidelines establish a set of norms and common code of conduct that provide for a safe and welcoming space for everyone. </p>


      <p>At Ocureel, we prioritize safety, diversity, inclusion, and authenticity. We encourage creators to celebrate what makes them unique and viewers to engage with what inspires them; we believe that a safe environment helps everyone do so openly. We prize the global nature of our community and strive to take into account the breadth of cultural norms where we operate. We also aim to cultivate an environment for genuine interactions by encouraging authentic content on Ocureel.</p>

      <p> Our Community Guidelines apply to everyone and everything on Ocureel. We proactively enforce them using a mix of technology and human moderation and aim to do so before people report potentially violative content to us. We also encourage our community members to use the tools we provide on Ocureel to report any content or account they believe violates our Community Guidelines. </p>

      <p>We will remove any content – including video, audio, livestream, images, comments, links, or other text – that violates our Community Guidelines. Individuals are notified of our decisions and can appeal them if they believe no violation has occurred. We will temporarily or permanently ban accounts and/or users that are involved in severe or repeated on-platform violations; we may also consider actions on other platforms and offline behavior in these decisions. Circumstances that involve any instance of a threat of real-world harm to human life that is specific, credible, and imminent may be reported to law enforcement authorities. </p>

      <p>The full Ocureel experience is for people 16 and older, and we actively remove accounts of people we suspect are under this age.</p>

      <p> Our algorithms are designed with trust and safety in mind. For some content, we may reduce discoverability, including by redirecting search results, or making videos ineligible for recommendation in the main feed. More information can be found below in the Ineligible for the feed section. </p>

      <p>At the same time, we recognize that some content that would normally be removed per our Community Guidelines may be in the public interest. Therefore, we may allow exceptions under certain limited circumstances, such as educational, documentary, scientific, artistic, or satirical content, content in fictional or professional settings, counter speech, or content that otherwise enables individual expression on topics of social importance. To minimize the potentially negative impact of graphic content, we may first include safety measures such as an “opt-in” screen or warning. </p>

      <p> In consultation with relevant stakeholders, we update our Community Guidelines from time to time to evolve alongside new behaviors and risks, as part of our commitment to keeping Ocureel a safe place for creativity and joy.</p>

      <h4> Minor safety </h4>
      <p>We are deeply committed to protecting the safety of minors on our platform. Ocureel defines a minor as any person under the age of 18. We prohibit activities that perpetuate the abuse, harm, endangerment, or exploitation of minors on Ocureel. Any content, including animation or digitally created or manipulated media, that depicts abuse, exploitation, or endangerment of minors is a violation on our platform and will be removed when detected. We report child sexual abuse material (CSAM) and supporting evidence to the National Center for Missing & Exploited Children (NCMEC) and to any additional relevant legal authorities.</p>

      <p> Our users must meet the minimum age requirements to use Ocureel, as stipulated in our Terms of Service. When an underage account is identified, we remove it. Given our platform is designed with the safety of minors in mind, some of our features are age restricted. Account holders who are under the age of 18 cannot receive referral payouts. </p>

      <h4> Sexual exploitation of minors </h4>
      <p> Ocureel will take action on any content or accounts involving CSAM or sexual exploitation of a minor. Sexual exploitation of minors includes any abuse of a position of power or trust for sexual purposes, including profiting financially, socially, sexually, or politically from the exploitation of a minor. CSAM is defined as any visual depiction of sexually explicit nudity or conduct of a minor, whether captured by predatory adults, peers, or self-generated by minors.</p>

      <h4> Do not post, upload, download, stream, or share:</h4>
      <p> Content that shares, reshares, offers to trade or sell, or directs users off platform to obtain or distribute CSAM Content that engages with minors in a sexualized way, or otherwise sexualizes a minor (e.g., via product features like duets) Content that depicts, solicits, glorifies, or encourages child abuse imagery including nudity, sexualized minors, or sexual activity with minors Content that depicts, promotes, normalizes, or glorifies pedophilia or the sexual assault of a minor Content that re-victimized or capitalizes on minor victims of abuse by third party reshares or reenactments of assault or confessions </p>

      <h4> Grooming behavior </h4>
      <p> Grooming behaviors are those in which an adult builds an emotional relationship with a minor in order to gain the minor's trust for the purposes of future or ongoing sexual contact, sexual abuse, trafficking, or other exploitation. These behaviors may include: flattery, requests for contact on or off platform, requests for personal information, solicitation of minor sexual abuse material, sexual solicitations or comments, and gift-giving. </p>
      <h4>Do not post, upload, stream, or share: </h4>
      <h5>Grooming advances</h5>
      <p>Content that depicts, promotes, normalizes, or glorifies grooming behaviors Content that solicits real-world contact between a minor and an adult or between minors with a significant age difference Content that displays or offers nudity to minors Content that solicits minors to connect with an adult on another platform, website, or other digital space Any solicitation of nude imagery or sexual contact, through blackmail or other means of coercion </p>

      <h4>Nudity and sexual activity involving minors</h4>
      <p> Nudity and sexual activity involving minors include content that is overtly revealing of breasts, genitals, anus, or buttocks, or behaviors that mimic, imply, or display sex acts involving minors. We do not allow the depiction, including digitally created or manipulated content, of nudity or sexual activity. </p>

      <h4>Do not post, upload, stream, or share: </h4>
      <p>Content that depicts or implies minor sexual activities including penetrative and non-penetrative sex, oral sex, or intimate kissing Content that depicts sexual arousal or sexual stimulation involving a minor Content that depicts a sexual fetish involving a minor Content that depicts exposed genitals, buttocks, the pubic region, or female nipples of a minor Content that contains sexually explicit language depicting or describing a minor Content depicting a minor that contains sexually explicit song lyrics Content with sexually explicit dancing of a minor, including twerking, breast shaking, pelvic thrusting, or fondling the groin or breasts of oneself or another Content depicting a minor undressing Content depicting a minor in minimal clothing that is not situationally relevant to the location Sexualized comments, emojis, text, or other graphics used to veil or imply nudity or sexual activity of a minor </p>
      <h4> Harmful activities by minors </h4>
      <p>Harmful minor activities include the possession or consumption of substances prohibited for minors, the misuse of legal substances, engagement in illegal activities, and participation in activities, physical challenges, or dares that may threaten the well-being of minors. We remove any such content from our platform. </p>
      <h4>Do not post, upload, stream, or share: </h4>
      <p>Content that suggests, depicts, imitates, or promotes the possession or consumption of alcoholic beverages, tobacco, or drugs by a minor Content that offers instruction targeting minors on how to buy, sell, or trade alcohol, tobacco, or controlled substances Content that depicts or promotes activities that may jeopardize youth well-being, including physical challenges, dares, or stunts </p>
      <h4>Physical and psychological harm of minors </h4>
      <p>Behaviors that place minors at risk of physical or psychological harm include physical abuse, neglect, child endangerment, and psychological disparagement. We remove any such content from our platform. </p>

      <h4> Do not post, upload, stream, or share: </h4>
      <p>Content that depicts or promotes physical abuse, neglect, endangerment, or psychological disparagement of minors </p>
      <h4> Crimes against children</h4>
      <p> We do not allow users who have been convicted of crimes against children to have an account on our platform. These crimes include: sexual assault, molestation, murder, physical abuse or neglect, abduction, international parental kidnapping, trafficking, exploitation of minors for prostitution, live online sexual abuse of a minor, sexual exploitation of minors in the context of travel and tourism, attempts to obtain or distribute CSAM, and the production, possession, or distribution of CSAM. If we discover any such users, we ban the account. Any self-disclosed user information that states the account holder is a pedophile or minor sex offender will be taken at face value and the account will be deleted. </p>

      <h4>Dangerous acts and challenges</h4>
      <p>We do not permit users to share content depicting, promoting, normalizing or glorifying dangerous acts that may lead to serious injury or death. We also do not allow content which promotes or endorses collective participation in dangerous or harmful activities that violate any aspect of our Community Guidelines. </p>

      <p> We define dangerous acts or other dangerous behavior as activities conducted in a non-professional context or without the necessary skills and safety precautions that may lead to serious injury or death for the user or the public. This includes amateur stunts or dangerous challenges. </p>

      <h4>Do not post, upload, stream, or share: </h4>
      <p> Content that shows the potentially inappropriate use of dangerous tools or objects Content that depicts dangerous driving behavior Content that depicts or promotes ingesting substances that are not meant for consumption and could lead to severe harm Content that describes or provides instructional detail on how to perform a dangerous activity Dangerous games, dares, challenges, or stunts that might lead to injury or property damage</p>

      <h4> Suicide, self-harm, and disordered eating</h4>
      <p> We care deeply about the health and well-being of the individuals who make up our community. We do not allow content depicting, promoting, normalizing, or glorifying activities that could lead to suicide, self-harm, or disordered eating. However, we do support members of our community sharing their personal experiences with these issues in a safe way to raise awareness and find community support. We also encourage individuals who are struggling with thoughts of suicide or self-harm, or who know someone is seriously considering suicide, to immediately contact local emergency services or a suicide prevention hotline. In the event that our intervention could help a user who may be at risk of harming themselves, Ocureel may also alert local emergency services. </p>

      <h4>Suicide and self-harm </h4>

      <p>We remove content that depicts suicide, involves suicidal ideation, or that might encourage suicidal or self-injurious behavior. We also remove content that depicts attempted suicide or behavior likely to lead to self-inflicted death. We prohibit any form of content that promotes, normalizes, or glorifies suicide, provides instructions for suicide, or posts that portray a suicide as heroic or honorable. Circumstances that involve any instance of a threat of real-world harm to human life that is specific, credible, and imminent may be reported to law enforcement authorities. </p>

      <p> Content that encourages or promotes suicide or self-harm hoaxes are also not allowed. This includes alarming warnings that could cause panic and widespread harm. We will remove such warnings, while allowing content that seeks to dispel panic and promote accurate information about such hoaxes. Do not post, upload, stream, or share: Content that depicts, promotes, normalizes, or glorifies suicide or self-harm Content that provides instructions for suicide or how to engage in self-harm Suicide or self harm games, dares, challenges, pacts, or hoaxes </p>

      <h4> Disordered eating </h4>
      <p>Content that promotes unhealthy eating behaviors or habits that are likely to cause adverse health outcomes is not allowed on the platform. This includes content expressing desire for an eating disorder, sharing tips or coaching on disordered eating, and participation in unhealthy body measurement challenges.</p>
      <h4> Do not post, upload, stream, or share: </h4>
      <p>Content that depicts, promotes, normalizes, or glorifies disordered eating Content that depicts, promotes, normalizes, or glorifies any dangerous weight loss behaviors associated with disordered eating </p>

      <h4> Adult nudity and sexual activities</h4>
      <p> We strive to create a platform that feels welcoming and safe. We do not allow nudity, pornography, or sexually explicit content on our platform. We also prohibit content depicting or supporting non-consensual sexual acts, the sharing of non-consensual intimate imagery, and adult sexual solicitation. </p>

      <h4>Sexual exploitation</h4>
      <p> Sexual exploitation is defined as any actual or attempted abuse of a position of vulnerability, power, or trust for sexual purposes, including profiting monetarily, socially, or politically from the sexual exploitation of another. We do not permit sexually exploitative content. </p>

      <h4>Do not post, upload, stream, or share: </h4>
      <p> Content that depicts, solicits, promotes, normalizes, or glorifies non-consensual sexual acts or non-consensual touching, including rape and sexual assault Content that depicts, solicits, promotes, normalizes, or glorifies the sharing of non-consensual intimate imagery, including sexual images that are taken, created, or shared without consent Content that depicts, promotes, normalizes, or glorifies sexual violence Content that depicts, promotes, or glorifies sexual solicitation, including offering or asking for sexual partners, sexual chats or imagery, sexual services, premium sexual content, or sexcamming </p>

      <h4> Nudity and sexual activity involving adults</h4>

      <p> Nudity and sexual activity include content that is overtly revealing of breasts, genitals, anus, or buttocks, or behaviors that mimic, imply, or display sex acts. We do not allow depictions, including digitally created or manipulated content, of nudity or sexual activity. We are mindful that some content may be offensive or culturally inappropriate in certain regions or may not be suitable for users of all ages. </p>

      <h4>Do not post, upload, stream, or share: </h4>
      <p>Content that explicitly or implicitly depicts sexual activities including penetrative and non-penetrative sex, oral sex, or erotic kissing Content that depicts sexual arousal or sexual stimulation Content that depicts a sexual fetish Content that depicts genitals, buttocks, the pubic region, or female nipples Content that contains sexually explicit language for sexual gratification </p>
      <h4>Bullying and harassment</h4>
      <p> We believe in an inclusive community and individual expression without fear of abuse. We do not tolerate members of our community being shamed, bullied, or harassed. Abusive content or behavior can cause severe psychological distress and will be removed from our platform. </p>

      <h4>Abusive behavior </h4>
      <p>We remove expressions of abuse, including threats or degrading statements intended to mock, humiliate, embarrass, intimidate, or hurt an individual. This prohibition extends to the use of Ocureel features. To enable expression about matters of public interest, critical comments of public figures may be allowed; however, serious abusive behavior against public figures is prohibited. </p>
      <h4> Do not post, upload, stream, or share:</h4>
      <p> Content that insults another individual, or disparages an individual on the basis of attributes such as intellect, appearance, personality traits, or hygiene Content that encourages coordinated harassment Content that disparages victims of violent tragedies Content that uses Ocureel interactive features (e.g., duet) to degrade others Content that depicts willful harm or intimidation, such as cyberstalking or trolling Content that wishes death, serious disease, or other serious harm on an individual </p>

      <h4>Sexual harassment </h4>
      <p>Sexual harassment involves unwanted or inappropriate sexual behavior directed at another individual. We do not allow content that glorifies, normalizes or promotes sexual harassment, regardless of the user's intent.</p>

      <h4> Do not post, upload, stream, or share: </h4>
      <p>Content that attempts to make unwanted sexual contact Content that disparages another person’s sexual activity Content that simulates sexual activity with another person, either verbally, in text (including emojis), or through the use of any in-app features Content that alters or morphs an image of another individual to portray or imply sexual suggestiveness or engagement in sexual activity Content that reveals, or threatens to reveal, details of a person's private sexual life, including digital content, sexual history, and names of previous sexual partners Content that exposes, or threatens to expose, a person's sexual orientation without their consent</p>
      <h4> Threats of hacking, doxxing, and blackmail</h4>
      <p> Threatening to hack or dox with an intent to harass or blackmail another individual can cause serious emotional distress and other offline harm. We define doxxing as the act of collecting and publishing personal data or personally identifiable information (PII) for malicious purposes. We consider these online behaviors as forms of abuse and do not allow them on our platform.</p>
      <h4> Do not post, upload, stream, or share: </h4>
      <p>Content that threatens to reveal personal data or personally identifiable information (PII), including residential address, private email address, private phone number, bank statement, social security number, or passport number Content that threatens to blackmail an individual or to hack an individual's account Content that incites or encourages others to hack or reveal another person's account, personal data, or personally identifiable information (PII) An individual's account, personal data, or personally identifiable information to encourage others to abuse, troll, or harass that individual</p>

      <h4> Hateful behavior </h4>
      <p>Ocureel is a diverse and inclusive community that has no tolerance for discrimination. We do not permit content that contains hate speech or involves hateful behavior, and we remove it from our platform. We ban accounts and/or users that engage in severe or multiple hate speech violations or that are associated with hate speech off the Ocureel platform.</p>

      <h4> Attacks and slurs on the basis of protected attributes </h4>
      <p>We define hate speech or behavior as content that attacks, threatens, incites violence against, or otherwise dehumanizes an individual or a group on the basis of the following protected attributes:</p><p> Race Ethnicity National origin Religion Caste Sexual orientation Sex Gender Gender identity Serious disease Disability Immigration status</p>

      <p> Slurs are defined as derogatory terms that are intended to disparage groups or individuals based on any protected attributes listed above. To minimize the spread of egregiously offensive terms, we remove all slurs from our platform, unless the terms are reappropriated, used self-referentially (i.e., by members of the protected group), or used in a way that does not disparage (e.g., educational context). </p>

      <h4>Do not post, upload, stream, or share:</h4>
      <p> Content claiming individuals or groups with protected attributes are physically, mentally, or morally inferior or referring to them as criminals, animals, inanimate objects, or other non-human entities Content promoting or justifying violence, exclusion, segregation, or discrimination against them Content that includes the use of non-self referential slurs Content that targets transgender or non-binary individuals through misgendering or deadnaming Content that depicts harm inflicted upon an individual or a group on the basis of a protected attribute </p>

      <h4>Hateful ideology </h4>
      <p> Hateful ideologies are those that demonstrate clear hostility toward people because of their protected attributes. Hateful ideologies  are incompatible with the inclusive and supportive community that our platform provides and we remove content that promotes them.</p>

      <h4>Do not post, upload, stream, or share: </h4>
      <p>Content that praises, promotes, glorifies, or supports any hateful ideology (e.g., white supremacy, misogyny, anti-LGBTQ, antisemitism) Content that contains names, symbols, logos, flags, slogans, uniforms, gestures, salutes, illustrations, portraits, songs, music, lyrics, or other objects related to a hateful ideology Content that promotes, supports, or advertises conversion therapy or related program Content that denies well-documented and violent events have taken place affecting groups with protected attributes (e.g., Holocaust denial) Claims of supremacy over a group of people with reference to other protected attributes Conspiracy theories used to justify hateful ideologies .</p>

      <h4>Violent extremism</h4>
      <p> We take a firm stance against enabling violence on or off Ocureel. We do not allow people to use our platform to threaten or incite violence, or to promote violent extremist organizations, individuals, or acts. When there is a threat to public safety or an account is used to promote or glorify off-platform violence, we ban the account. When warranted, we will report threats to relevant legal authorities. To effectively protect our community, we may consider off-platform behavior to identify violent extremist organizations and individuals on our platform. If we find such organizations or individuals, we will ban their accounts. </p>
      <h4>Threats and incitement to violence</h4>
      <p> We consider incitement to violence as advocating for, directing, or encouraging other people to commit violence. We do not allow threats of violence or incitement to violence on our platform that may result in serious physical harm. </p>
      <h4>Do not post, upload, stream, or share: </h4>
      <p> Statements of intent to inflict physical injuries on an individual or a group Statements or imagery that encourage others to commit or that advocate for violence Conditional or aspirational statements that encourage other people to commit violence Calls to bring weapons to a location with the intent to intimidate or threaten an individual or group with violence Instructions on how to make or use weapons that may incite violence </p>

      <h4>Violent extremist organizations and individuals </h4>
      <p>We do not allow organizations or individuals on our platform who promote or engage in violence, including terrorist organizations, organized hate groups, criminal organizations, and other non-state armed groups that target civilians. </p>
      <h4>Terrorist organizations</h4>
      <p> Terrorists and terrorist organizations are non-state actors that threaten violence, use violence, and/or commit serious crimes (such as crimes against humanity) against civilian populations in pursuit of political, religious, ethnic, or ideological objectives. </p>

      <h4> Organized hate groups </h4>
      <p>We use the term “organized hate” to refer to those individuals and organizations who attack people based on protected attributes, such as race, ethnicity, national origin, religion, caste, sexual orientation, sex, gender, gender identity, or immigration status. We consider attacks to include actions that incite violence or hatred, that aim to dehumanize individuals or groups, or that embrace a hateful ideology. </p>

      <h4>Criminal organizations </h4>
      <p>Criminal organizations are transnational, national, or local groups that have engaged in serious crimes, including violent crimes (e.g., homicide, rape, robbery, assault), trafficking (e.g., human, organ, drug, weapons), kidnapping, financial crimes (e.g., extortion, blackmail, fraud, money laundering), or cybercrime. </p>

      <h4> Do not post, upload, stream, or share: </h4>
      <p>Content that praises, promotes, glorifies, or supports violent acts or extremist organizations or individuals Content that encourages participation in, or intends to recruit individuals to, violent extremist organizations Content with names, symbols, logos, flags, slogans, uniforms, gestures, salutes, illustrations, portraits, songs, music, lyrics, or other objects meant to represent violent extremist organizations or individuals </p>
      <h4>Integrity and authenticity</h4>
      <p> We believe that trust forms the foundation of our community. We do not allow activities that may undermine the integrity of our platform or the authenticity of our users. We remove content or accounts that involve spam or fake engagement, impersonation, or misleading information that causes significant harm. </p>

      <h4>Spam and fake engagement </h4>
      <p> Fake engagement includes any content or activity that seeks to artificially inflate popularity on the platform. We prohibit any attempts to manipulate the platform to increase interaction metrics. </p>
      <h4>Do not: </h4>
      <p>Share instructions on how to artificially increase views, likes, followers, shares, or comments Engage in selling or buying views, likes, followers, shares, or comments Promote artificial traffic generation services Operate multiple Ocureel accounts under false or fraudulent pretenses to distribute commercial spam Create malicious software or modify code to artificially increase views, likes, followers, shares, or comments</p>
      <h4> Impersonation </h4>
      <p>We do not allow accounts that pose as another person or entity in a deceptive manner. When we confirm a report of impersonation, we may ask the user to revise the profile or may ban the account. We do allow accounts that are clearly parody, commentary, or fan-based, such as where the username indicates that it is a fan, commentary, or parody account and not affiliated with the subject of the account. </p>
      <h4>Do not: </h4>
      <p> Pose as another person or entity by using someone else's name, biographical details, or profile picture in a misleading manner</p>
      <h4>Harmful misinformation </h4>
      <p>Misinformation is defined as content that is inaccurate or false. We will remove misinformation that causes significant harm to individuals, our community, or the larger public regardless of intent. Significant harm includes serious physical injury, illness, or death; severe psychological trauma; large-scale property damage, and the undermining of public trust in civic institutions and processes such as governments, elections, and scientific bodies. This does not include simply inaccurate information, myths, or commercial or reputational harm. </p>
      <h4>Do not post, upload, stream, or share: </h4>
      <p> Misinformation that incites hate or prejudice Misinformation related to emergencies that induces panic Medical misinformation that can cause harm to an individual's physical health Content that misleads community members about elections or other civic processes Conspiratorial content including content that attacks a specific person or a protected group, includes a violent call to action, or denies a violent or tragic event occurred Digital Forgeries (Synthetic Media or Manipulated Media) that mislead users by distorting the truth of events and cause significant harm to the subject of the video, other persons, or society </p>
      <h4> Do not:</h4>
      <p> Engage in coordinated inauthentic behavior such as the use of multiple accounts to exert influence and sway public opinion while misleading individuals, our community, or our systems about the account's identity, location, relationships, popularity, or purpose </p>
      <h4>Illegal activities and regulated goods </h4>
      <p> We work to ensure Ocureel does not enable activities that violate laws or regulations. We prohibit the trade, sale, promotion, and use of certain regulated goods, as well as the promotion or facilitation of criminal activities, including human exploitation. Content may be removed if it relates to activities or goods that are regulated or illegal in the majority of the region or world. </p>
      <h4>Criminal activities </h4>
      <p>Criminal activities cover a wide spectrum of acts punishable by law, including theft, assault, human exploitation, counterfeiting, and other harmful behavior. To prevent such behavior from being normalized, imitated, or facilitated, we remove content that promotes or enables criminal activities.</p>
      <h4> Do not post, upload, stream, or share: </h4>
      <p> Content that promotes acts of physical harm, such as assault or kidnapping Content that risks the safety of others, including swatting Content that promotes human exploitation, including human smuggling, bonded labor, domestic servitude, sex trafficking, or prostitution Content that promotes vandalism or damage to property Content that promotes the poaching or illegal trade of wildlife Content that offers the purchase, sale, trade, or solicitation of unlawfully acquired or counterfeit goods Content that provides instructions on how to conduct criminal activities that result in harm to people, animals, or property </p>
      <h4>Weapons</h4>
      <p> We do not allow the depiction, promotion, or trade of firearms, ammunition, firearm accessories, or explosive weapons. We also prohibit instructions on how to manufacture those weapons. We may allow depiction when appearing in educational contexts (e.g., as part of a museum's collection), involving authorized government personnel (e.g., a police officer) or used in a safe and controlled environment (e.g., shooting range, recreational hunting).</p>



      <h4> Do not post, upload, stream, or share: </h4>
      <p>Content that displays firearms, firearm accessories, ammunition, or explosive weapons Content that offers the purchase, sale, trade, or solicitation of firearms, accessories, ammunition, explosive weapons, or instructions on how to manufacture them Drugs, controlled substances, alcohol, and tobacco We do not allow the depiction, promotion, or trade of drugs or other controlled substances. The trade of tobacco and alcohol products is also prohibited on the platform. Do not post, upload, stream, or share: Content that depicts or promotes drugs, drug consumption, or encourages others to make, use, or trade drugs or other controlled substances Content that offers the purchase, sale, trade, or solicitation of drugs or other controlled substances, alcohol or tobacco products (including vaping products, smokeless or combustible tobacco products, synthetic nicotine products, E-cigarettes, and other ENDS [Electronic Nicotine Delivery Systems]) Content that provides information on how to buy illegal or controlled substances Content that depicts or promotes the misuse of legal substances, or instruction on how to make homemade substances, in an effort to become intoxicated </p>

      <h4>Frauds and scams </h4>
      <p>We do not permit anyone to exploit our platform to take advantage of the trust of users and bring about financial or personal harm. We remove content that deceives people in order to gain an unlawful financial or personal advantage, including schemes to defraud individuals or steal assets. </p>
      <h4>Do not post, upload, stream, or share: </h4>
      <p>Content that promotes phishing Content that promotes Ponzi, multi-level marketing, or pyramid schemes Content that promotes investment schemes with promise of high returns, fixed betting, or any other types of scams </p>

      <h4>Gambling</h4>
      <p> We do not allow content promoting gambling services, or that could be perceived as advertising for casinos, sports betting, or any other commercial gambling activity.</p>

      <h4> Do not post, upload, stream, or share: </h4>
      <p>Content that promotes casinos, sports betting, poker, lotteries, gambling-related software and apps, or other gambling services </p>

      <h4>Privacy, personal data, and personally identifiable information (PII)</h4>
      <p> We do not allow content that violates the confidentiality of personal data or personally identifiable information (e.g., social security information, phone numbers, physical addresses). We remove content that depicts personal data or personally identifiable information (PII) from the platform.</p>

      <h4> Do not post, upload, stream, or share: </h4>
      <p>Content that contains personal data or personally identifiable information (PII) </p>

      <h4>Violent and graphic content </h4>

      <p>Ocureel is a platform that celebrates creativity but not shock value or violence. We do not allow content that is gratuitously shocking, graphic, sadistic, or gruesome or that promotes, normalizes, or glorifies extreme violence or suffering on our platform. When it is a threat to public safety, we ban the account and, when warranted, we will report it to relevant legal authorities. </p>

      <h4>Do not post, upload, stream, or share: </h4>
      <p>Content of humans that depicts: violent or graphic deaths or accidents dismembered, mutilated, charred, or burned human remains gore in which an open wound or injury is the core focus real-world physical violence, fighting, or torture Content of animals that depicts: the slaughter or other non-natural death of animals dismembered, mutilated, charred, or burned animal remains animal cruelty and gore </p>

      <h4>Copyright and trademark infringement</h4>
      <p> Copyright is a legal right that protects original works of authorship (e.g., music, videos) and original expression of an idea (e.g., the specific way a video or music is expressed or created), although it does not protect underlying ideas or facts. A trademark is a word, symbol, slogan, or design that identifies and distinguishes the source of a product or service. We encourage everyone to create and share original content. Content that infringes someone else's intellectual property rights is prohibited on our platform and will be removed if we become aware of it. The use of copyrighted work under certain circumstances, such as the fair use doctrine or other applicable laws, or the use of a trademark to reference, lawfully comment, criticize, parody, make a fan page, or review a product or service, may not be considered a violation of our policies.</p>

      <h4>Do not post, upload, stream, or share: </h4>
      <p>Content that violates or infringes someone else's copyrights, trademarks, or other intellectual property rights</p>
      <h4> Platform security</h4>
      <p> A top priority for Ocureel is the safety and security of our users, creators, business partners, vendors, and employee data, including their personal information, accounts, profiles, content, and other proprietary information, as well as our product and services. We do not allow access to the Ocureel platform -- which includes our website, app, network, and associated infrastructure or networks -- through unauthorized methods, or to obtain sensitive confidential commercial or personal information. Any attempt to undermine or abuse the security, integrity or reliability of our platform, products, or services is expressly prohibited. </p>

      <h4>Do not:</h4>
      <p> Attempt to access the Ocureel platform in an unauthorized manner, and do not create fake or misleading versions of the Ocureel platform Create or distribute malicious files, content, or messages that contain viruses, Trojan horses, worms, logic bombs, or other materials that may be harmful to the community or platform Use automated scripts, web crawling, software, deceptive techniques, or any other way to attempt to obtain, acquire, or request login credentials or other sensitive information, including non-public data, from Ocureel or its users Leverage Ocureel accounts under false or fraudulent pretenses to distribute spam, phishing, or smishing content in an attempt to perpetrate cybercrime or gain unauthorized access to others’ content, accounts, systems, or data Modify, adapt, translate, reverse engineer, disassemble, decompile, or create any derivative products based on Ocureel, including any files, tables or documentation, or attempt to regenerate any source code, algorithms, methods, or techniques embodied in Ocureel Provide access to your account credentials to others or enable others to conduct activities against our Community Guidelines Click on suspicious links or engage in requests for information about your Ocureel account details, passwords, verification qualification, financial, or other personal information </p>

      <h4> Ineligible for the feed</h4>
      <p> The goal of the feed is to provide original content that honors our mission of inspiring authenticity and genuine connection. Each account holder’s feed is based on a personalized recommendation system. Our recommendation system is designed with user safety as a primary consideration, meaning that some content may not be eligible for recommendation. While the spontaneity of the feed is what makes Ocureel unique, the feed is intended for a general audience that includes everyone from our teenage users to great grandparents. We consider the breadth of our audience when we determine what content is eligible for algorithmic promotion on the platform. Provided that it does not violate local laws, the following types of content may be allowed on our platform, searchable, and viewed in Following feeds but not eligible for recommendation. </p>

      <h4>Minor safety </h4>

      <p>Minors’ sense of judgment and identity mature as they develop. To provide teens with additional room for identity exploration and expression in digital spaces, content uploaded by users under the age of 16 is not eligible for recommendation. We strive to encourage healthy development across all ages. The promotion of cosmetic surgery to minors may lead to higher rates of body dissatisfaction. Accordingly, such content -- including before-and-after videos, videos of surgical procedures, and messages discussing elective cosmetic surgery without warning of risks -- are ineligible for the feed of all users under the age of 18.</p>

      <h4> Dangerous stunts and sports </h4>
      <p> Certain activities can be risky or dangerous when replicated without safety precautions, which could lead to physical harm. Content that includes dangerous stunts, or extreme sports performed by non-professionals, may be ineligible. (We remove content that depicts dangerous acts and challenges performed by non-professionals, which may lead to serious injury or death for the user or the public). </p>

      <h4>Overtly sexualized content </h4>
      <p>We are mindful that not all content may be suitable for all users (particularly our teenage users) and/or may be culturally inappropriate in certain regions. To help maintain a comfortable and age-appropriate experience, content that is overtly sexually suggestive may not be eligible for recommendation. This would include content that depicts implied nudity, sexualizes body parts, or is blatantly erotic or sensual (e.g., strip teases). </p>

      <h4>Tobacco and alcohol products</h4>
      <p> Ocureel is deeply committed to protecting the safety of minors on our platform. Content promoting, mentioning, or depicting alcohol products consumed by persons of legal drinking age but done so in a dangerous fashion may not be eligible for recommendation. Content depicting the use of tobacco products by adults or mentioning controlled substances is not eligible for recommendation. Please remember that content which suggests, depicts, imitates, or promotes the possession or consumption of alcoholic beverages, tobacco, or drugs by a minor is prohibited. Content that offers instruction targeting minors on how to buy, sell, or trade alcohol, tobacco, or controlled substances is prohibited per our Community Guidelines as well. </p>

      <h4>Violent and graphic content </h4>
      <p>Our community celebrates creativity, but shock value isn't everyone's preference. Content that can cause discomfort, shock or disgust to viewers may be ineligible for the feed, including scary effects, jump scares, makeup that realistically replicates gory wounds, or depictions of bodily functions. Most violent and graphic content is not allowed on Ocureel; however, in certain situations we may not remove some types of this content such as depictions of graphic deaths, accidents or fighting when real world events are being documented and it is in the public interest. Since this content isn't appropriate for all audiences, it will not be eligible for recommendation and the content will include an “opt-in” screen or warning. </p>

      <h4> Spam, inauthentic, or misleading content </h4>
      <p>We value authenticity and accuracy. We make ineligible for the feed any content that tricks or manipulates users in order to inauthentically increase followers, likes, views, or other engagement metrics on the platform, including follow-to-follow, like-to-like, and misleading or manipulating users into clicking like or share buttons. Conspiratorial content that counters generally accepted beliefs and casts blame on a group or entity (rather than any living individual) or that includes potentially misleading and harmful content about current, unfolding events where details are still developing, are also ineligible for recommendation. </p>

      <h4>Unoriginal, low-quality, and QR code content </h4>
      <p>Original and entertaining content form the core of the Ocureel community. To maintain the positive experience our users expect from the Ocureel platform, unoriginal and low-quality content is ineligible for recommendation. We consider content not original if it is imported or uploaded from Ocureel, other platforms, or other sources including television, movies, or webcasts, and the user has not added new, creative edits. One indicator that the content is not original is a visible watermark or superimposed logo. Low quality content includes extremely short clips, static images, and exclusively-GIF based videos. Content that includes QR codes is usually ineligible for the feed because it can lead users to harmful websites or apps, though we make exceptions in certain circumstances where that risk is low (e.g., e-commerce).</p>
      <p> If you come across content or accounts that you believe may violate our Community Guidelines, please let us know so we can review and take appropriate action.</p>

    </div>
  )
}

export default Index